Repository boostcamp-2020/Project16-E-Account-Book, pull requests merged in 2020-12, with the labels that each got.

#69 FE-feat-mypage-ui 마이페이지 UI 틀 작업 완료
  client/src/components/atoms/button/HexagonButton/HexagonButton.tsx
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.tsx
  client/src/components/atoms/p/LeftNormalText/LeftNormalText.tsx
  client/src/components/molecules/Modal/Modal.stories.tsx
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/Modal/index.ts
  client/src/components/organisms/MyPageMenu/MyPageMenu.tsx
  client/src/components/organisms/MyPageUserMenu/MyPageUserMenu.stories.tsx
  client/src/components/organisms/MyPageUserMenu/MyPageUserMenu.tsx
  client/src/components/organisms/MyPageUserMenu/index.ts
  client/src/theme/color.ts
  client/src/views/MyPage.tsx
Labels: ✨ feature, 🐝 Front-end

#70 FE-feat dropdown ui
  client/src/components/atoms/input/Input/Input.tsx
  client/src/components/molecules/DateWithText/DateWithText.stories.tsx
  client/src/components/molecules/DateWithText/DateWithText.tsx
  client/src/components/molecules/DateWithText/index.ts
  client/src/components/molecules/InputWithText/InputWithText.stories.tsx
  client/src/components/molecules/InputWithText/InputWithText.tsx
  client/src/components/molecules/InputWithText/index.ts
  client/src/components/molecules/MenuWithText/MenuWithText.stories.tsx
  client/src/components/molecules/MenuWithText/MenuWithText.tsx
  client/src/components/molecules/MenuWithText/index.ts
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.tsx
  client/src/components/organisms/TransactionAddBox/TransactionAddBox.stories.tsx
  client/src/components/organisms/TransactionAddBox/TransactionAddBox.tsx
  client/src/components/organisms/TransactionAddBox/index.ts
  client/src/theme/color.ts
Labels: ✨ feature, 🐝 Front-end

#71 FE-feat-createAccountbookPage & 콜리타임
  client/config/env.js
  client/src/App.tsx
  client/src/components/atoms/button/CircleIconButton/CircleIconButton.stories.tsx
  client/src/components/atoms/button/OAuthButton/OAuthButton.stories.tsx
  client/src/components/atoms/checkbox/CheckBox/CheckBox.stories.tsx
  client/src/components/atoms/div/ColorLabel/ColorLabel.stories.tsx
  client/src/components/atoms/div/RoundShortChips/RoundShortChips.stories.tsx
  client/src/components/atoms/div/SquircleCard/SquircleCard.stories.tsx
  client/src/components/atoms/div/SquircleShortChips/SquircleShortChips.stories.tsx
  client/src/components/atoms/hr/Line/Line.stories.tsx
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.stories.tsx
  client/src/components/atoms/input/Input/Input.stories.tsx
  client/src/components/atoms/p/CenterLargeText/CenterLargeText.stories.tsx
  client/src/components/atoms/p/CenterNormalText/CenterNormalText.stories.tsx
  client/src/components/atoms/p/CenterSmallText/CenterSmallText.stories.tsx
  client/src/components/atoms/textarea/TextArea/TextArea.stories.tsx
  client/src/components/organisms/ColoredBackground/ColoredBackground.stories.tsx
  client/src/components/organisms/ColoredBackground/ColoredBackground.tsx
  client/src/components/organisms/ColoredBackground/index.ts
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end, 🔥 콜리타임

#68 FE-feat-set Jwt Cookie & MainPage
  client/src/App.tsx
  client/src/components/atoms/div/SquircleCard/SquircleCard.tsx
  client/src/components/organisms/TopNavBar/TopNavBar.tsx
  client/src/utils/queryParser.ts
  client/src/views/MainPage.tsx
  server/src/oauth/controller.ts
Labels: ✨ feature, 🐝 Front-end, 🛠 fix

#73 FE-feat-modal Redux를 이용한 modal 기능 구현, 마이페이지 모달 생성
  client/.storybook/main.js
  client/.storybook/preview.js
  client/config/webpack.config.js
  client/src/actions/modal/type.ts
  client/src/components/atoms/button/HexagonButton/HexagonButton.tsx
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/organisms/AccountBookAcceptModal/AccountBookAcceptModal.stories.tsx
  client/src/components/organisms/AccountBookAcceptModal/AccountBookAcceptModal.tsx
  client/src/components/organisms/AccountBookAcceptModal/index.ts
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.stories.tsx
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
  client/src/components/organisms/CreditCardEditModal/index.ts
  client/src/components/organisms/MyPageMenu/MyPageMenu.tsx
  client/src/components/organisms/UserInfoSettingModal/UserInfoSettingModal.stories.tsx
  client/src/components/organisms/UserInfoSettingModal/UserInfoSettingModal.tsx
  client/src/components/organisms/UserInfoSettingModal/index.ts
  client/src/index.tsx
  client/src/reducers/modal.ts
  client/src/reducers/rootReducer.ts
  client/src/store/index.ts
  client/src/views/MyPage.tsx
  client/tsconfig.paths.json
Labels: ✨ feature, 🐝 Front-end

#72 FE-feat-mainpage
  client/src/components/atoms/div/SquircleCard/SquircleCard.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/views/MainPage.tsx
Labels: ✨ feature, 🐝 Front-end

#75 BE-feat-Mysql 접근 및 token 인증 middleware 구현
  client/src/App.tsx
  client/src/utils/cookieParser.ts
  client/src/views/MainPage.tsx
  server/app.ts
  server/model/db.ts
  server/src/interface/index.ts
  server/src/interface/user.ts
  server/src/middleware/verifyToken.ts
  server/src/model/db.ts
  server/src/model/privateBookQuery.ts
  server/src/model/userQuery.ts
  server/src/oauth/controller.ts
  server/src/oauth/router.ts
  server/src/oauth/service.ts
  server/src/user/controller.ts
  server/src/user/router.ts
  server/src/user/service.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end

#74 FE-feat-createAccountbookPage-ui
  client/src/components/molecules/ChangeAccountbookColorCard/ChangeAccountbookColorCard.stories.tsx
  client/src/components/molecules/ChangeAccountbookColorCard/ChangeAccountbookColorCard.tsx
  client/src/components/molecules/ChangeAccountbookColorCard/index.ts
  client/src/components/molecules/InviteAccountbookCard/InviteAccountbookCard.stories.tsx
  client/src/components/molecules/InviteAccountbookCard/InviteAccountbookCard.tsx
  client/src/components/molecules/InviteAccountbookCard/index.ts
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.stories.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.tsx
  client/src/components/organisms/CreateAccountbookFormBox/index.ts
  client/src/components/organisms/CreateAccountbookSetting/CreateAccountbookSetting.stories.tsx
  client/src/components/organisms/CreateAccountbookSetting/CreateAccountbookSetting.tsx
  client/src/components/organisms/CreateAccountbookSetting/index.ts
  client/src/components/organisms/TopNavBar/TopNavBar.tsx
  client/src/theme/color.ts
  client/src/utils/color.ts
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end

#77 BE-refactor : query export 변경
  server/src/model/db.ts
  server/src/model/query/index.ts
  server/src/model/query/privateBookQuery.ts
  server/src/model/query/userQuery.ts
  server/src/oauth/controller.ts
  server/src/oauth/service.ts
Labels: 💻 Back-end, 🛠 fix

#76 FE-feat-month-tab 내역화면 연-월 UI 구축
  client/src/actions/date/type.ts
  client/src/components/molecules/MonthNav/MonthNav.stories.tsx
  client/src/components/molecules/MonthNav/MonthNav.tsx
  client/src/components/molecules/MonthNav/index.ts
  client/src/reducers/date.ts
  client/src/reducers/rootReducer.ts
Labels: ✨ feature, 🐝 Front-end

#81 FE-feat calendar 기능을 위한 함수 구현
  client/src/components/organisms/Calendar/Calendar.stories.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/Calendar/index.ts
  client/src/utils/firstDayOfWeek.ts
  client/src/utils/isLeapYear.ts
Labels: ✨ feature, 🐝 Front-end

#80 FULL-feat login render
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.tsx
  client/src/utils/api.ts
  client/src/views/LoginPage.tsx
  server/app.ts
  server/src/oauth/controller.ts
  server/src/oauth/router.ts
  server/src/oauth/service.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🛠 fix

#79 FE-feat-내역,달력,통계 페이지 생성 및 연동
  client/src/App.tsx
  client/src/views/Accountbook.tsx
  client/src/views/Calendar.tsx
  client/src/views/List.tsx
  client/src/views/Statistics.tsx
Labels: ✨ feature, 🐝 Front-end

#78 FE-feat-new transaction-button 거래 내역 추가 버튼 구현
  client/.storybook/preview.js
  client/src/App.tsx
  client/src/components/atoms/button/CreateButton/CreateButton.stories.tsx
  client/src/components/atoms/button/CreateButton/CreateButton.tsx
  client/src/components/atoms/button/NavButton/NavButton.tsx
  client/src/components/molecules/CenterContent/CenterContent.tsx
  client/src/components/organisms/NewTransactionButton/NewTransactionButton.stories.tsx
  client/src/components/organisms/NewTransactionButton/NewTransactionButton.tsx
  client/src/components/organisms/NewTransactionButton/index.ts
  client/src/views/CalendarPage.tsx
  client/src/views/MainPage.tsx
  client/src/views/StatisticsPage.tsx
  client/src/views/TransactionPage.tsx
  client/src/views/TransactionPostPage.tsx
Labels: ✨ feature, 🐝 Front-end

#82 BE-feat-social-api 소셜 가계부 목록 조회 API 구현
  server/app.ts
  server/src/interface/social.ts
  server/src/interface/user.ts
  server/src/middleware/verifyToken.ts
  server/src/model/query/index.ts
  server/src/model/query/socialBookQuery.ts
  server/src/oauth/controller.ts
  server/src/oauth/service.ts
  server/src/router.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
  server/src/utils/response.ts
Labels: ✨ feature, 💻 Back-end

#84 FE-feat-transaction-new-ui
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.tsx
  client/src/components/organisms/CreateTransactionHeader/CreateTransactionHeader.stories.tsx
  client/src/components/organisms/CreateTransactionHeader/CreateTransactionHeader.tsx
  client/src/components/organisms/CreateTransactionHeader/index.ts
  client/src/components/organisms/CreateTransactionMenu/CreateTransactionMenu.stories.tsx
  client/src/components/organisms/CreateTransactionMenu/CreateTransactionMenu.tsx
  client/src/components/organisms/CreateTransactionMenu/index.ts
  client/src/components/organisms/TransactionAddBox/TransactionAddBox.stories.tsx
  client/src/components/organisms/TransactionAddBox/TransactionAddBox.tsx
  client/src/components/organisms/TransactionAddBox/index.ts
  client/src/components/organisms/TransactionForm/TransactionForm.stories.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/components/organisms/TransactionForm/index.ts
  client/src/theme/color.ts
  client/src/views/TransactionPostPage.tsx
Labels: ✨ feature, 🐝 Front-end

#85 FE-feat-날짜별 가계부 내역 상세 조회기능 구현
  client/src/components/atoms/div/RoundShortChips/RoundShortChips.tsx
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.tsx
  client/src/components/molecules/TransactionInfo/TransactionInfo.stories.tsx
  client/src/components/molecules/TransactionInfo/TransactionInfo.tsx
  client/src/components/molecules/TransactionInfo/index.ts
  client/src/components/molecules/TransactionTotal/TransactionTotal.stories.tsx
  client/src/components/molecules/TransactionTotal/TransactionTotal.tsx
  client/src/components/molecules/TransactionTotal/index.ts
  client/src/components/organisms/DailyTransactionModal/DailyTransactionModal.stories.tsx
  client/src/components/organisms/DailyTransactionModal/DailyTransactionModal.tsx
  client/src/components/organisms/DailyTransactionModal/index.ts
Labels: ✨ feature, 🐝 Front-end

#83 FULL-feat-creditCardEditModal 결재수단 관리 modal 구현
  client/src/assets/svg/minus.svg
  client/src/components/atoms/button/IconButton/IconButton.tsx
  client/src/components/atoms/hr/Line/Line.stories.tsx
  client/src/components/atoms/hr/Line/Line.tsx
  client/src/components/molecules/CreditCard/CreditCard.stories.tsx
  client/src/components/molecules/CreditCard/CreditCard.tsx
  client/src/components/molecules/CreditCard/index.ts
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/organisms/CreditCardEditCardList/CreditCardEditCardList.stories.tsx
  client/src/components/organisms/CreditCardEditCardList/CreditCardEditCardList.tsx
  client/src/components/organisms/CreditCardEditCardList/index.ts
  client/src/components/organisms/CreditCardEditFormBox/CreditCardEditFormBox.stories.tsx
  client/src/components/organisms/CreditCardEditFormBox/CreditCardEditFormBox.tsx
  client/src/components/organisms/CreditCardEditFormBox/index.ts
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
Labels: ✨ feature, 🐝 Front-end

#86 FE-feat calendar ui 구축
  client/src/components/atoms/p/ExpenditureText/ExpenditureText.tsx
  client/src/components/atoms/p/IncomeText/IncomeText.tsx
  client/src/components/molecules/CheckBoxWithNumber/CheckBoxWithNumber.stories.tsx
  client/src/components/molecules/CheckBoxWithNumber/CheckBoxWithNumber.tsx
  client/src/components/molecules/CheckBoxWithNumber/index.ts
  client/src/components/molecules/DayBox/DayBox.stories.tsx
  client/src/components/molecules/DayBox/DayBox.tsx
  client/src/components/molecules/DayBox/index.ts
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.stories.tsx
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.tsx
  client/src/components/molecules/MoneyOfWeek/index.ts
  client/src/components/molecules/Weeks/Weeks.stories.tsx
  client/src/components/molecules/Weeks/Weeks.tsx
  client/src/components/molecules/Weeks/index.ts
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/utils/firstDayOfWeek.ts
  client/src/utils/makeMonth.ts
  client/src/utils/numberOfMonth.ts
Labels: ✨ feature, 🐝 Front-end

#92 콜리타임 - 3주차
  client/src/components/atoms/button/HomeButton/HomeButton.stories.tsx
  client/src/components/atoms/button/HomeButton/HomeButton.tsx
  client/src/components/atoms/button/RoundShortButton/RoundShortButton.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.tsx
  client/src/components/organisms/TopNavBar/TopNavBar.tsx
Labels: 🐝 Front-end, 🔥 콜리타임

#87 FE-feat-logout 구현
  client/src/components/atoms/button/TextButton/TextButton.tsx
  client/src/components/organisms/MyPageUserMenu/MyPageUserMenu.tsx
Labels: ✨ feature, 🐝 Front-end

#88 콜리타임- 3주차
  client/src/components/atoms/button/OAuthButton/OAuthButton.tsx
  client/src/components/atoms/textarea/TextArea/TextArea.tsx
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.tsx
Labels: 🐝 Front-end, 🔥 콜리타임

#90 FE-feat-calendar UI
  client/src/components/atoms/p/ExpenditureText/ExpenditureText.tsx
  client/src/components/atoms/p/IncomeText/IncomeText.tsx
  client/src/components/molecules/DayBox/DayBox.tsx
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.tsx
  client/src/components/molecules/Weeks/Weeks.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/utils/sliceArray.ts
Labels: ✨ feature, 🐝 Front-end

#89 BE-feat-ReadDailyTransaction
  server/.env.sample
  server/src/middleware/verifyToken.ts
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#106 Fe feat accountbook store
  client/src/App.tsx
  client/src/actions/accountbook/type.ts
  client/src/actions/category/type.ts
  client/src/actions/user/type.ts
  client/src/components/organisms/MyPageUserMenu/MyPageUserMenu.tsx
  client/src/interfaces/category.ts
  client/src/reducers/accountbook.ts
  client/src/reducers/category.ts
  client/src/reducers/rootReducer.ts
  client/src/reducers/user.ts
  client/src/utils/api.ts
  client/src/utils/axios.ts
  client/src/views/LoginPage.tsx
  client/src/views/MainPage.tsx
  client/src/views/NotFoundPage.tsx
Labels: ✨ feature, 🐝 Front-end

#108 Full-feat-init-store store값 초기화 및 토큰 검증
  client/src/App.tsx
  client/src/actions/accountbook/type.ts
  client/src/actions/category/type.ts
  client/src/actions/payment/type.ts
  client/src/actions/user/type.ts
  client/src/components/molecules/UserImages/UserImages.tsx
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.stories.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/interfaces/accountbook.ts
  client/src/interfaces/payment.ts
  client/src/reducers/accountbook.ts
  client/src/reducers/category.ts
  client/src/reducers/payment.ts
  client/src/reducers/user.ts
  client/src/utils/api.ts
  client/src/utils/axios.ts
  client/src/utils/random.ts
  client/src/views/MainPage.tsx
  client/src/views/MyPage.tsx
  server/src/model/query/userQuery.ts
  server/src/oauth/service.ts
  server/src/router.ts
  server/src/user/controller.ts
  server/src/user/router.ts
  server/src/user/service.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🛠 fix

#107 BE-feat-transactionList privateAccountbook 연,월 내역 조회
  server/src/model/query/privateBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
  server/src/router.ts
Labels: ✨ feature, 💻 Back-end

#110 FE-feat-calendar state
  client/src/actions/transaction/type.ts
  client/src/components/molecules/DayBox/DayBox.tsx
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.tsx
  client/src/components/molecules/TransactionInfo/TransactionInfo.tsx
  client/src/components/organisms/Calendar/Calendar.stories.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/DailyTransactionModal/DailyTransactionModal.stories.tsx
  client/src/components/organisms/DailyTransactionModal/DailyTransactionModal.tsx
  client/src/reducers/rootReducer.ts
  client/src/reducers/transaction.ts
  client/src/utils/api.ts
  client/src/views/CalendarPage.tsx
Labels: ✨ feature, 🐝 Front-end

#111 Full fix chore
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.tsx
  client/src/reducers/rootReducer.ts
  client/src/utils/api.ts
  server/src/interface/transaction.ts
  server/src/model/query/privateBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
Labels: 🐝 Front-end, 💻 Back-end, 🛠 fix, 🦟 bug

#109 BE-feat-월별 통계 API 구현
  server/.eslintrc.json
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
  server/src/utils/date.ts
Labels: ✨ feature, 💻 Back-end

#112 FE-feat-transaction-add TransactionForm 디자인 및 기능 개선
  client/src/components/atoms/div/ToggleButton/ToggleButton.stories.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.tsx
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.stories.tsx
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.tsx
  client/src/components/atoms/input/Input/Input.tsx
  client/src/components/molecules/DateWithText/DateWithText.stories.tsx
  client/src/components/molecules/DateWithText/DateWithText.tsx
  client/src/components/molecules/InputWithText/InputWithText.tsx
  client/src/components/molecules/MenuWithText/MenuWithText.stories.tsx
  client/src/components/molecules/MenuWithText/MenuWithText.tsx
  client/src/components/organisms/CreateTransactionHeader/CreateTransactionHeader.tsx
  client/src/components/organisms/CreateTransactionMenu/CreateTransactionMenu.tsx
  client/src/components/organisms/NewTransactionButton/NewTransactionButton.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.stories.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/reducers/rootReducer.ts
  client/src/views/TransactionPostPage.tsx
Labels: ✨ feature, 🐝 Front-end

#113 Be feat statistic category api
  server/src/interface/social.ts
  server/src/model/query/privateBookQuery.ts
  server/src/model/query/socialBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
  server/src/utils/accountbook.ts
  server/src/utils/message.ts
Labels: ✨ feature, 💻 Back-end

#114 FE-feat transaction edit page 구현
  client/src/components/organisms/EditTransactionMenu/EditTransactionMenu.stories.tsx
  client/src/components/organisms/EditTransactionMenu/EditTransactionMenu.tsx
  client/src/components/organisms/EditTransactionMenu/index.ts
  client/src/views/TransactionEditPage.tsx
Labels: ✨ feature, 🐝 Front-end

#116 FE-feat-최근 4개월 월별통계 차트 구현
  client/src/components/atoms/graph/TwoBarGraph/TwoBarGraph.stories.tsx
  client/src/components/atoms/graph/TwoBarGraph/TwoBarGraph.tsx
  client/src/components/atoms/graph/TwoBarGraph/index.ts
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.stories.tsx
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.tsx
  client/src/components/organisms/FourMonthStatistics/index.ts
  client/src/utils/api.ts
  client/src/utils/calcMonth.ts
  client/src/views/StatisticsPage.tsx
  server/src/socialBook/controller.ts
Labels: ✨ feature, 🐝 Front-end

#115 FE-feat transaction list UI
  client/src/components/molecules/DailyTotal/DailyTotal.stories.tsx
  client/src/components/molecules/DailyTotal/DailyTotal.tsx
  client/src/components/molecules/DailyTotal/index.ts
  client/src/components/molecules/DailyTransaction/DailyTransaction.stories.tsx
  client/src/components/molecules/DailyTransaction/DailyTransaction.tsx
  client/src/components/molecules/DailyTransaction/index.ts
  client/src/components/molecules/DayBox/DayBox.tsx
  client/src/components/molecules/TransactionInfo/TransactionInfo.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/DailyTransactionModal/DailyTransactionModal.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.stories.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/components/organisms/MonthTransaction/index.ts
  client/src/utils/api.ts
  client/src/views/CalendarPage.tsx
  client/src/views/TransactionPage.tsx
Labels: ✨ feature, 🐝 Front-end

#117 FE-feat-statistics-page 초기 호출 데이터 설정
  client/src/views/StatisticsPage.tsx
Labels: ✨ feature, 🐝 Front-end

#118 FE-feat-createAccountButton 가계부 생성 페이지 수정 및 생성 버튼 기능개발
  client/src/components/atoms/textarea/TextArea/TextArea.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.stories.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.tsx
  client/src/utils/api.ts
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end

#120 BE-feat-createAccountButton 가계부 생성 api 개발
  client/src/utils/api.ts
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#122 FE-feat-transactionadd 거래내역 추가 기능 구현
  client/.eslintrc.json
  client/src/components/atoms/button/IconDetailButton/IconDetailButton.tsx
  client/src/components/atoms/button/RoundLongButton/RoundLongButton.tsx
  client/src/components/atoms/button/RoundShortButton/RoundShortButton.tsx
  client/src/components/atoms/button/TextButton/TextButton.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.tsx
  client/src/components/atoms/graph/TwoBarGraph/TwoBarGraph.tsx
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.tsx
  client/src/components/atoms/input/Input/Input.tsx
  client/src/components/atoms/p/ExpenditureText/ExpenditureText.tsx
  client/src/components/atoms/p/IncomeText/IncomeText.tsx
  client/src/components/atoms/p/NumberText/NumberText.tsx
  client/src/components/molecules/DateWithText/DateWithText.stories.tsx
  client/src/components/molecules/DateWithText/DateWithText.tsx
  client/src/components/molecules/InputWithText/InputWithText.stories.tsx
  client/src/components/molecules/InputWithText/InputWithText.tsx
  client/src/components/molecules/MenuWithText/MenuWithText.tsx
  client/src/components/molecules/TwoByTwoChips/TwoByTwoChips.tsx
  client/src/components/organisms/CreateTransactionMenu/CreateTransactionMenu.stories.tsx
  client/src/components/organisms/CreateTransactionMenu/CreateTransactionMenu.tsx
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.stories.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/interfaces/transaction.ts
  client/src/utils/api.ts
  client/src/utils/date.ts
  client/src/utils/number.ts
  client/src/utils/numberToMoney.ts
  client/src/views/StatisticsPage.tsx
  client/src/views/TransactionEditPage.tsx
  client/src/views/TransactionPostPage.tsx
  server/src/privateBook/controller.ts
  server/src/socialBook/controller.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🛠 fix

#121 BE-feat-socialTransactionList 소셜 가계부 연,월 조회 API 구현
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#119 FULL-feat-private 가계부 4개월 통계 대응
  client/src/utils/api.ts
  client/src/views/StatisticsPage.tsx
  server/src/model/query/privateBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end

#127 BE-feat private status api
  client/src/App.tsx
  client/src/actions/user/type.ts
  client/src/reducers/user.ts
  client/src/utils/api.ts
  client/src/views/MainPage.tsx
  server/src/model/query/privateBookQuery.ts
  server/src/model/query/userQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
  server/src/user/controller.ts
  server/src/user/router.ts
  server/src/user/service.ts
  server/src/utils/makeAnalysisData.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🛠 fix

#126 FULL-feat-pastFiveWeeksStatistics 구현
  client/.eslintrc.json
  client/src/components/atoms/graph/RowBarGraph/RowBarGraph.stories.tsx
  client/src/components/atoms/graph/RowBarGraph/RowBarGraph.tsx
  client/src/components/atoms/graph/RowBarGraph/index.ts
  client/src/components/organisms/FiveWeekStatistics/FiveWeekStatistics.stories.tsx
  client/src/components/organisms/FiveWeekStatistics/FiveWeekStatistics.tsx
  client/src/components/organisms/FiveWeekStatistics/index.ts
  client/src/utils/api.ts
  client/src/views/StatisticsPage.tsx
  server/.eslintrc.json
  server/src/model/query/privateBookQuery.ts
  server/src/model/query/socialBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
  server/src/utils/date.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end

#129 FE-fix-week4-doyeon
  client/src/components/atoms/button/HomeButton/HomeButton.tsx
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.tsx
  client/src/components/atoms/input/Input/Input.tsx
  client/src/components/molecules/DailyTotal/DailyTotal.tsx
  client/src/components/molecules/DailyTransaction/DailyTransaction.tsx
  client/src/components/molecules/DayBox/DayBox.tsx
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.tsx
  client/src/components/molecules/Weeks/Weeks.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.stories.tsx
  client/src/components/organisms/DailyTransactionModal/DailyTransactionModal.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/index.tsx
  client/src/theme/color.ts
  client/src/views/AccountbookPage.tsx
  client/src/views/MainPage.tsx
Labels: 🐝 Front-end, 🛠 fix

#128 FE-Fix-메인페이지 리팩토링
  client/src/components/atoms/button/CreateButton/CreateButton.tsx
  client/src/components/molecules/CardNumberText/CardNumberText.tsx
  client/src/components/molecules/TwoByTwoChips/TwoByTwoChips.tsx
  client/src/components/molecules/UserImages/UserImages.tsx
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/views/MainPage.tsx
Labels: 🐝 Front-end, 🛠 fix

#130 FE-fix-login page error
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.tsx
  client/src/views/LoginPage.tsx
Labels: 🐝 Front-end, 🛠 fix

#131 FE-fix-week4-jjy
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.tsx
  client/src/components/molecules/MonthNav/MonthNav.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.tsx
  client/src/components/organisms/CreateAccountbookSetting/CreateAccountbookSetting.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/views/AccountbookPage.tsx
Labels: 🐝 Front-end, 🛠 fix

#132 FE-fix-user-data 개인 가계부 내역 연동 및 코드 리팩토링
  client/src/components/atoms/button/SquircleShortButton/SquircleShortButton.tsx
  client/src/components/molecules/CardInfo/CardInfo.tsx
  client/src/components/molecules/TwoByTwoChips/TwoByTwoChips.stories.tsx
  client/src/components/molecules/TwoByTwoChips/TwoByTwoChips.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.tsx
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/components/organisms/MyPageUserMenu/MyPageUserMenu.tsx
  client/src/interfaces/accountbook.ts
  client/src/utils/api.ts
  client/src/utils/calcMonth.ts
  client/src/utils/date.ts
  client/src/utils/firstDayOfWeek.ts
  client/src/utils/isLeapYear.ts
  client/src/utils/makeMonth.ts
  client/src/utils/numberOfMonth.ts
  client/src/views/CalendarPage.tsx
  client/src/views/MainPage.tsx
  client/src/views/MyPage.tsx
  client/src/views/StatisticsPage.tsx
  client/src/views/TransactionPage.tsx
Labels: ✨ feature, 🐝 Front-end, 🛠 fix

#133 FE-Fix-jiwoo
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.tsx
  client/src/components/molecules/MenuWithText/MenuWithText.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
Labels: 🐝 Front-end, 🛠 fix

#134 FE-fix-week4-jjy 추가 수정
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.tsx
  client/src/components/atoms/p/ExpenditureText/ExpenditureText.tsx
  client/src/components/atoms/p/IncomeText/IncomeText.tsx
  client/src/components/molecules/MonthNav/MonthNav.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/NewTransactionButton/NewTransactionButton.tsx
  client/src/views/AccountbookPage.tsx
  client/src/views/CreateAccountbookPage.tsx
  client/src/views/StatisticsPage.tsx
Labels: 🐝 Front-end, 🛠 fix

#135 FE-fix calendar modal, ui
  client/src/actions/transaction/type.ts
  client/src/components/atoms/p/ExpenditureText/ExpenditureText.tsx
  client/src/components/atoms/p/IncomeText/IncomeText.tsx
  client/src/components/molecules/DayBox/DayBox.tsx
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/reducers/transaction.ts
  client/src/shared/global.tsx
  client/src/views/CalendarPage.tsx
  client/src/views/TransactionPage.tsx
Labels: 🐝 Front-end, 🛠 fix

#136 Data-feat-create 테스트용 데이터 생성 코드 작성
  data/.gitignore
  data/README.md
  data/gen-private-expenditure.py
  data/gen-private-income.py
  data/gen-user-payment.py
Labels: ✨ feature, 💻 Back-end

#137 FE-fix transaction post page
  client/src/actions/previous/type.ts
  client/src/components/organisms/NewTransactionButton/NewTransactionButton.tsx
  client/src/reducers/previous.ts
  client/src/reducers/rootReducer.ts
  client/src/views/TransactionEditPage.tsx
  client/src/views/TransactionPostPage.tsx
Labels: 🐝 Front-end, 🛠 fix

#138 FE-fix-doyeon 배포용 디자인 개선 및 month 초기화 오류 해결
  client/src/actions/date/type.ts
  client/src/components/atoms/button/TextButton/TextButton.tsx
  client/src/components/atoms/img/UserImage/UserImage.tsx
  client/src/components/molecules/MonthNav/MonthNav.tsx
  client/src/components/molecules/UserImages/UserImages.tsx
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/reducers/date.ts
  client/src/views/AccountbookPage.tsx
  client/src/views/MainPage.tsx
  client/src/views/NotificationPage.tsx
Labels: ✨ feature, 🛠 fix

#139 FE-Feat-SMS 파싱 기능 구현 및 각종 컴포넌트 리팩토링
  client/src/components/molecules/DailyTotal/DailyTotal.tsx
  client/src/components/molecules/DailyTransaction/DailyTransaction.tsx
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/TransactionInfo/TransactionInfo.tsx
  client/src/components/organisms/CreateTransactionHeader/CreateTransactionHeader.tsx
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/components/organisms/NewTransactionButton/NewTransactionButton.tsx
  client/src/components/organisms/SmsParsingModal/SmsParsingModal.stories.tsx
  client/src/components/organisms/SmsParsingModal/SmsParsingModal.tsx
  client/src/components/organisms/SmsParsingModal/index.ts
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/views/StatisticsPage.tsx
Labels: ✨ feature, 🐝 Front-end, 🛠 fix

#140 FULL-feat-creditCardEditModal 결재수단 관리 모달 UI 수정 및 관련 API 구현
  client/src/components/atoms/div/ColumnFlexContainer/ColumnFlexContainer.tsx
  client/src/components/molecules/CreditCard/CreditCard.tsx
  client/src/components/organisms/CreditCardEditCardList/CreditCardEditCardList.stories.tsx
  client/src/components/organisms/CreditCardEditCardList/CreditCardEditCardList.tsx
  client/src/components/organisms/CreditCardEditFormBox/CreditCardEditFormBox.stories.tsx
  client/src/components/organisms/CreditCardEditFormBox/CreditCardEditFormBox.tsx
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
  client/src/utils/api.ts
  server/src/model/query/paymentQuery.ts
  server/src/payment/controller.ts
  server/src/payment/router.ts
  server/src/payment/service.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🦟 bug

#141 FE-feat 막대차트 구현
  client/src/components/atoms/graph/StickGraph/StickGraph.stories.tsx
  client/src/components/atoms/graph/StickGraph/StickGraph.tsx
  client/src/components/atoms/graph/StickGraph/index.ts
  client/src/components/molecules/StickWithText/StickWithText.stories.tsx
  client/src/components/molecules/StickWithText/StickWithText.tsx
  client/src/components/molecules/StickWithText/index.ts
  client/src/components/organisms/StickChart/StickChart.stories.tsx
  client/src/components/organisms/StickChart/StickChart.tsx
  client/src/components/organisms/StickChart/index.ts
  client/src/theme/color.ts
  client/src/utils/api.ts
  client/src/views/StatisticsPage.tsx
Labels: ✨ feature, 🐝 Front-end

#145 콜리타임 4주차 - 개인가계부 분석 내역 API response 수정
  client/.env.sample
  client/src/components/atoms/graph/CircleGraph/CircleGraph.tsx
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/interfaces/accountbook.ts
  client/src/views/MainPage.tsx
  server/src/privateBook/controller.ts
  server/src/privateBook/service.ts
Labels: 🐝 Front-end, 💻 Back-end, 🔥 콜리타임, 🛠 fix

#147 콜리타임 4주차 FE 개선
  client/src/components/atoms/div/ToggleButton/ToggleButton.tsx
  client/src/components/atoms/graph/StickGraph/StickGraph.tsx
  client/src/components/molecules/MonthNav/MonthNav.tsx
  client/src/components/molecules/StickWithText/StickWithText.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/views/StatisticsPage.tsx
Labels: 🐝 Front-end, 🔥 콜리타임

#144 [콜리타임]-상단바 Z-index 문제 수정
  client/src/components/organisms/TopNavBar/TopNavBar.tsx
Labels: 🐝 Front-end, 🔥 콜리타임

#146 BE-feat-내역 수정 API 구현
  server/src/model/query/privateBookQuery.ts
  server/src/model/query/socialBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#143 콜리타임 4주차
  server/src/oauth/controller.ts
  server/src/oauth/service.ts
Labels: ✨ feature, 💻 Back-end, 🔥 콜리타임

#142 [콜리타임]-BE-Naver OAuth Default 이미지 생성
  server/.env.sample
  server/src/interface/user.ts
  server/src/oauth/service.ts
Labels: 💻 Back-end, 🔥 콜리타임, 🛠 fix

#148 [콜리타임]-FE-localstorage 상태관리
  client/src/App.tsx
  client/src/actions/previous/type.ts
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/components/organisms/MyPageUserMenu/MyPageUserMenu.tsx
  client/src/components/organisms/NewTransactionButton/NewTransactionButton.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/reducers/previous.ts
  client/src/reducers/rootReducer.ts
  client/src/utils/cookieParser.ts
  client/src/views/CalendarPage.tsx
  client/src/views/TransactionPostPage.tsx
Labels: 🐝 Front-end, 🔥 콜리타임, 🛠 fix

#150 BE-feat-accountbook-accept 소셜 가계부 초대 목록조회, 승인/거절, 초대취소 API 개발
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
  server/src/utils/message.ts
Labels: ✨ feature, 💻 Back-end

#151 BE-statistic trend graph API
  server/.env.sample
  server/src/model/query/privateBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
Labels: ✨ feature, 💻 Back-end

#149 BE-feat-transaction 삭제 API 구현
  server/src/model/query/socialBookQuery.ts
  server/src/privateBook/controller.ts
  server/src/privateBook/router.ts
  server/src/privateBook/service.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#152 BE-feat-소셜가계부 초대 API 구현 및 유저 목록 API 구현
  server/src/model/query/userQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
  server/src/user/controller.ts
  server/src/user/router.ts
  server/src/user/service.ts
Labels: ✨ feature, 💻 Back-end

#153 BE-feat-trendgraph social API
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#156 FE-feat-accountbook-accept 소셜 가계부 승인/거절 모달 UI 구축
  client/src/components/atoms/p/LeftNormalText/LeftNormalText.tsx
  client/src/components/molecules/InvitationCard/InvitationCard.stories.tsx
  client/src/components/molecules/InvitationCard/InvitationCard.tsx
  client/src/components/molecules/InvitationCard/index.ts
  client/src/components/organisms/AccountBookAcceptModal/AccountBookAcceptModal.stories.tsx
  client/src/components/organisms/AccountBookAcceptModal/AccountBookAcceptModal.tsx
  client/src/components/organisms/AccountBookAcceptModal/index.ts
  client/src/components/organisms/InvitationManagementModal/InvitationManagementModal.stories.tsx
  client/src/components/organisms/InvitationManagementModal/InvitationManagementModal.tsx
  client/src/components/organisms/InvitationManagementModal/index.ts
  client/src/components/organisms/UserInfoSettingModal/UserInfoSettingModal.tsx
  client/src/interfaces/accountbook.ts
  client/src/utils/api.ts
  client/src/utils/date.ts
  client/src/views/MyPage.tsx
  server/src/model/query/socialBookQuery.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end

#155 FE-feat-social-edit page 생성
  client/src/App.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.stories.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/interfaces/accountbook.ts
  client/src/views/AccountBookEditPage.tsx
  client/src/views/MainPage.tsx
Labels: ✨ feature, 🐝 Front-end

#154 FULL-feat-creditCardEditModal 결재 수단 관리 기능 구현
  client/src/components/molecules/CreditCard/CreditCard.stories.tsx
  client/src/components/molecules/CreditCard/CreditCard.tsx
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
  client/src/utils/api.ts
  server/src/model/query/paymentQuery.ts
  server/src/payment/controller.ts
  server/src/payment/router.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end

#176 FE-feat-invitation 소셜 가계부 승인/거절 페이지 완성
  client/src/components/molecules/InvitationCard/InvitationCard.stories.tsx
  client/src/components/molecules/InvitationCard/InvitationCard.tsx
  client/src/components/organisms/InvitationManagementModal/InvitationManagementModal.stories.tsx
  client/src/components/organisms/InvitationManagementModal/InvitationManagementModal.tsx
  client/src/utils/api.ts
  client/src/utils/axios.ts
  client/src/utils/date.ts
  client/src/views/MyPage.tsx
  server/src/model/query/socialBookQuery.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🛠 fix

#177 Full-feat-creditCardEditModal 최종 기능 구현
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
  client/src/utils/api.ts
  server/src/model/query/paymentQuery.ts
  server/src/model/query/privateBookQuery.ts
  server/src/model/query/socialBookQuery.ts
  server/src/payment/controller.ts
  server/src/payment/router.ts
  server/src/payment/service.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🛠 fix

#181 FE-feat-pie-chart 파이 차트 구현
  client/src/components/atoms/button/CircleIconButton/CircleIconButton.tsx
  client/src/components/atoms/button/IconButton/IconButton.tsx
  client/src/components/atoms/button/OAuthButton/OAuthButton.tsx
  client/src/components/atoms/button/RoundButton/RoundButton.tsx
  client/src/components/atoms/button/RoundLongButton/RoundLongButton.tsx
  client/src/components/atoms/button/RoundShortButton/RoundShortButton.tsx
  client/src/components/atoms/checkbox/CheckBox/CheckBox.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.tsx
  client/src/components/atoms/graph/PieGraph/PieGraph.stories.tsx
  client/src/components/atoms/graph/PieGraph/PieGraph.tsx
  client/src/components/atoms/graph/PieGraph/index.ts
  client/src/components/molecules/ChangeAccountbookColorCard/ChangeAccountbookColorCard.tsx
  client/src/components/molecules/InviteAccountbookCard/InviteAccountbookCard.tsx
  client/src/components/molecules/Modal/Modal.tsx
  client/src/components/molecules/StickWithText/StickWithText.tsx
  client/src/components/organisms/FiveWeekStatistics/FiveWeekStatistics.tsx
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.tsx
  client/src/components/organisms/PieChart/PieChart.stories.tsx
  client/src/components/organisms/PieChart/PieChart.tsx
  client/src/components/organisms/PieChart/index.ts
  client/src/components/organisms/StickChart/StickChart.tsx
  client/src/theme/color.ts
  client/src/views/StatisticsPage.tsx
Labels: ✨ feature, 🐝 Front-end

#178 FE-feat-transaction 수정 / 삭제 기능 구현
  client/src/App.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.stories.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.tsx
  client/src/components/molecules/DailyTransaction/DailyTransaction.tsx
  client/src/components/organisms/DailyTransactionModal/DailyTransactionModal.tsx
  client/src/components/organisms/EditTransactionMenu/EditTransactionMenu.stories.tsx
  client/src/components/organisms/EditTransactionMenu/EditTransactionMenu.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/utils/api.ts
  client/src/views/StatisticsPage.tsx
  client/src/views/TransactionEditPage.tsx
Labels: ✨ feature, 🐝 Front-end

#182 FE-feat invitation modal
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.tsx
  client/src/components/molecules/InviteAccountbookCard/InviteAccountbookCard.stories.tsx
  client/src/components/molecules/InviteAccountbookCard/InviteAccountbookCard.tsx
  client/src/components/molecules/UserInviteCard/UserInviteCard.stories.tsx
  client/src/components/molecules/UserInviteCard/UserInviteCard.tsx
  client/src/components/molecules/UserInviteCard/index.ts
  client/src/components/organisms/CreateAccountbookSetting/CreateAccountbookSetting.tsx
  client/src/components/organisms/InvitationModal/InvitationModal.stories.tsx
  client/src/components/organisms/InvitationModal/InvitationModal.tsx
  client/src/components/organisms/InvitationModal/index.ts
  client/src/theme/color.ts
  client/src/utils/api.ts
  client/src/views/AccountbookEditPage.tsx
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end

#180 FE-feat-가계부 생성 페이지 생성 페이지 수정 및 색깔 선택 모달 구현
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.stories.tsx
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.tsx
  client/src/components/organisms/CreateAccountbookColorModal/index.ts
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.stories.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.tsx
  client/src/components/organisms/CreateAccountbookSetting/CreateAccountbookSetting.stories.tsx
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end, 🧶 refactor

#183 BE-feat-초대 대기중인 user 목록 API 구현
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#184 BE-feat-accountbook-eidt 소셜 가계부 정보 조회 및 수정 API 개발
  server/src/model/query/socialBookQuery.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: ✨ feature, 💻 Back-end

#185 FULL-feat-isSunday isSunday를 받아와서 Redux에 저장
  client/src/App.tsx
  client/src/actions/user/type.ts
  client/src/reducers/user.ts
  server/src/model/query/userQuery.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end

#188 FE-feat-test-login 테스트 로그인 버튼 구현
  client/src/assets/svg/test-logo.svg
  client/src/components/atoms/button/OAuthButton/OAuthButton.tsx
  client/src/components/molecules/DescriptionLine/DescriptionLine.tsx
  client/src/components/molecules/TestLoginButton/TestLoginButton.stories.tsx
  client/src/components/molecules/TestLoginButton/TestLoginButton.tsx
  client/src/components/molecules/TestLoginButton/index.ts
  client/src/components/organisms/TestLogin/TestLogin.stories.tsx
  client/src/components/organisms/TestLogin/TestLogin.tsx
  client/src/components/organisms/TestLogin/index.ts
  client/src/theme/color.ts
  client/src/utils/api.ts
  client/src/views/LoginPage.tsx
Labels: ✨ feature, 🐝 Front-end

#189 FE-feat 초대 모달 UI & 상태 구현 완료
  client/src/components/atoms/button/NavButton/NavButton.tsx
  client/src/components/molecules/UserInviteCard/UserInviteCard.stories.tsx
  client/src/components/molecules/UserInviteCard/UserInviteCard.tsx
  client/src/components/organisms/InvitationModal/InvitationModal.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/utils/api.ts
  client/src/views/AccountbookEditPage.tsx
Labels: ✨ feature, 🐝 Front-end

#187 BE-feat-테스트 계정 토큰생성용 API 구현
  server/.env.sample
  server/src/interface/user.ts
  server/src/oauth/controller.ts
  server/src/oauth/router.ts
Labels: ✨ feature, 💻 Back-end

#186 FE-refactor-초대하기 Modal 디자인 수정
  client/src/components/atoms/div/ColumnFlexContainer/ColumnFlexContainer.tsx
  client/src/components/molecules/UserInviteCard/UserInviteCard.tsx
  client/src/components/organisms/InvitationModal/InvitationModal.tsx
Labels: 🐝 Front-end, 🧶 refactor

#190 FULL-feat-createAccountbook-colorchange
  client/src/assets/svg/check.svg.tsx
  client/src/components/atoms/div/ColorLabel/ColorLabel.tsx
  client/src/components/molecules/ChangeAccountbookColorCard/ChangeAccountbookColorCard.tsx
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.tsx
  client/src/theme/colorList.ts
  client/src/utils/color.ts
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end

#192 FULL-feat-가계부 색깔 생성 모달 및 가계부 생성 기능 최종 구현
  client/src/components/atoms/div/ColorLabel/ColorLabel.stories.tsx
  client/src/components/atoms/div/ColorLabel/ColorLabel.tsx
  client/src/components/molecules/ColorLabelWithCheck/ColorLabelWithCheck.stories.tsx
  client/src/components/molecules/ColorLabelWithCheck/ColorLabelWithCheck.tsx
  client/src/components/molecules/ColorLabelWithCheck/index.ts
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.stories.tsx
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.tsx
  client/src/utils/color.ts
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end, 🦟 bug

#193 FE-refactor-내역/달력/통계 페이지 수정
  client/src/components/atoms/button/TextButton/TextButton.tsx
  client/src/components/molecules/DailyTotal/DailyTotal.tsx
  client/src/components/molecules/DailyTransaction/DailyTransaction.tsx
  client/src/components/molecules/DayBox/DayBox.tsx
  client/src/components/molecules/MoneyOfWeek/MoneyOfWeek.tsx
  client/src/components/molecules/MonthNav/MonthNav.tsx
  client/src/components/molecules/Weeks/Weeks.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/views/StatisticsPage.tsx
Labels: 🐝 Front-end, 🧶 refactor

#194 FE-feat-수정페이지 완성
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.stories.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.tsx
  client/src/utils/api.ts
  client/src/views/AccountbookEditPage.tsx
  client/src/views/CreateAccountbookPage.tsx
Labels: ✨ feature, 🐝 Front-end, 🛠 fix

#195 BE-fix-db-column database column 변경사항 반영 반영
  server/src/interface/user.ts
  server/src/model/query/paymentQuery.ts
  server/src/model/query/privateBookQuery.ts
  server/src/model/query/userQuery.ts
  server/src/oauth/controller.ts
  server/src/oauth/service.ts
Labels: 💻 Back-end, 🛠 fix, 🧶 refactor

#196 FE-리팩토링 마이페이지
  client/src/assets/svg/caution.svg
  client/src/components/molecules/PreparationBox/PreparationBox.stories.tsx
  client/src/components/molecules/PreparationBox/PreparationBox.tsx
  client/src/components/molecules/PreparationBox/index.ts
  client/src/components/organisms/CreditCardEditFormBox/CreditCardEditFormBox.tsx
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
  client/src/components/organisms/InvitationManagementModal/InvitationManagementModal.tsx
  client/src/components/organisms/UserInfoSettingModal/UserInfoSettingModal.tsx
Labels: 🐝 Front-end, 🧶 refactor

#197 FE-Fix-key warning 해결
  client/src/components/molecules/Weeks/Weeks.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
Labels: 🐝 Front-end, 🛠 fix, 🧶 refactor

#198 FULL-refactor-API url 및 순서 조정
  client/src/App.tsx
  client/src/utils/api.ts
  server/src/payment/router.ts
  server/src/privateBook/router.ts
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/user/controller.ts
  server/src/user/router.ts
Labels: 🐝 Front-end, 💻 Back-end, 🧶 refactor

#199 FE-refactor-transactionList key 오류 수정
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/views/TransactionPage.tsx
Labels: 🐝 Front-end, 🛠 fix, 🧶 refactor

#200 FE-design-refactor 메인화면 및 가계부 생성수정 화면 UI 개선
  client/src/components/atoms/div/ColorLabel/ColorLabel.tsx
  client/src/components/molecules/ChangeAccountbookColorCard/ChangeAccountbookColorCard.tsx
  client/src/components/molecules/ColorLabelWithCheck/ColorLabelWithCheck.tsx
  client/src/components/molecules/InviteAccountbookCard/InviteAccountbookCard.tsx
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.stories.tsx
  client/src/components/organisms/CreateAccountbookFormBox/CreateAccountbookFormBox.tsx
  client/src/components/organisms/CreateAccountbookSetting/CreateAccountbookSetting.tsx
  client/src/components/organisms/InvitationModal/InvitationModal.tsx
  client/src/components/organisms/SocialAccountBook/SocialAccountBook.tsx
  client/src/views/AccountbookEditPage.tsx
  client/src/views/CreateAccountbookPage.tsx
  client/src/views/StatisticsPage.tsx
  client/src/views/TransactionEditPage.tsx
Labels: 🐝 Front-end, 🛠 fix, 🧶 refactor

#202 FE-refactor-transactionList 내역 페이지 error 수정
  client/.eslintrc.json
  client/src/components/atoms/checkbox/CheckBox/CheckBox.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/views/AccountbookPage.tsx
  client/src/views/TransactionPage.tsx
Labels: 🐝 Front-end, 🙋‍♂️ help wanted, 🛠 fix, 🦟 bug, 🧶 refactor

#204 FE-feat-refactor 예외처리 및 리팩토링 진행
  client/public/index.html
  client/src/components/molecules/PreparationBox/PreparationBox.tsx
  client/src/components/organisms/CreateTransactionHeader/CreateTransactionHeader.tsx
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
  client/src/components/organisms/TransactionForm/TransactionForm.tsx
  client/src/views/NotificationPage.tsx
  server/src/socialBook/controller.ts
  server/src/socialBook/router.ts
  server/src/socialBook/service.ts
Labels: 🐝 Front-end, 💻 Back-end, 🛠 fix, 🧶 refactor

#201 FE-리팩토링 통계페이지
  client/src/components/atoms/graph/PieGraph/PieGraph.tsx
  client/src/components/molecules/MonthNav/MonthNav.tsx
  client/src/components/molecules/PreparationBox/PreparationBox.stories.tsx
  client/src/components/molecules/PreparationBox/PreparationBox.tsx
  client/src/components/molecules/StickWithText/StickWithText.tsx
  client/src/components/organisms/InvitationManagementModal/InvitationManagementModal.tsx
  client/src/components/organisms/PieChart/PieChart.tsx
  client/src/components/organisms/StickChart/StickChart.tsx
  client/src/components/organisms/UserInfoSettingModal/UserInfoSettingModal.tsx
  client/src/theme/color.ts
  client/src/utils/description.ts
  client/src/views/StatisticsPage.tsx
Labels: ✨ feature, 🐝 Front-end, 🛠 fix, 🧶 refactor

#203 FE-리팩토링 메인페이지
  client/src/components/atoms/graph/PieGraph/PieGraph.tsx
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.tsx
  client/src/components/molecules/UserImages/UserImages.tsx
  client/src/components/molecules/Weeks/Weeks.tsx
  client/src/components/organisms/Calendar/Calendar.tsx
  client/src/components/organisms/CreateAccountbookColorModal/CreateAccountbookColorModal.tsx
  client/src/components/organisms/CreditCardEditModal/CreditCardEditModal.tsx
  client/src/components/organisms/FiveWeekStatistics/FiveWeekStatistics.tsx
  client/src/components/organisms/FourMonthStatistics/FourMonthStatistics.tsx
  client/src/components/organisms/InvitationModal/InvitationModal.tsx
  client/src/components/organisms/MonthTransaction/MonthTransaction.tsx
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/components/organisms/StickChart/StickChart.tsx
  client/src/components/organisms/TestLogin/TestLogin.tsx
  client/src/utils/mainPageMent.ts
  client/src/utils/random.ts
  client/src/views/MainPage.tsx
  client/src/views/TransactionPage.tsx
Labels: ✨ feature, 🐝 Front-end, 🧶 refactor

#205 FE-스토리북 refactoring
  client/src/components/atoms/button/NavButton/NavButton.stories.tsx
  client/src/components/atoms/graph/PieGraph/PieGraph.stories.tsx
  client/src/components/atoms/graph/RowBarGraph/RowBarGraph.stories.tsx
  client/src/components/atoms/graph/StickGraph/StickGraph.stories.tsx
  client/src/components/atoms/graph/TwoBarGraph/TwoBarGraph.stories.tsx
Labels: 🐝 Front-end, 🛠 fix, 🧶 refactor
