Repository boostcamp-2020/Project16-E-Account-Book, pull requests merged in 2020-11, with the labels that each got.

#20 FE-CreateButton 생성, 코딩 컨벤션 적용, eslint 조정
  client/.eslintrc.json
  client/src/components/atoms/button/CreateButton/CreateButton.stories.tsx
  client/src/components/atoms/button/CreateButton/CreateButton.tsx
  client/src/components/atoms/button/CreateButton/index.ts
  client/src/theme/color.ts
Labels: ✨ feature, 🐝 Front-end, 🛠 fix

#22 FE-Atomic buttons 구현 & SVG 디렉토리 추가, 설정
  client/.storybook/main.js
  client/config/webpack.config.js
  client/package.json
  client/src/asserts/svg/github-logo.svg
  client/src/asserts/svg/naver-logo.svg
  client/src/components/atoms/button/HomeButton/HomeButton.stories.tsx
  client/src/components/atoms/button/HomeButton/HomeButton.tsx
  client/src/components/atoms/button/HomeButton/index.ts
  client/src/components/atoms/button/OAuthButton/OAuthButton.stories.tsx
  client/src/components/atoms/button/OAuthButton/OAuthButton.tsx
  client/src/components/atoms/button/OAuthButton/index.ts
  client/tsconfig.paths.json
Labels: ✨ feature, 🐝 Front-end

#23 Merge : 문서 작업내용 Develop에 병합
  .github/workflows/ReactBuildTest.yml
  sprint.md
Labels: 📝 documentation

#24 [FE]-OAuth 버튼 파일 타입 버그 수정
  client/src/components/atoms/button/OAuthButton/OAuthButton.tsx
Labels: 🛠 fix, 🦟 bug

#28 FE-fix-React build 오류 수정
  client/src/App.tsx
  client/src/reportWebVitals.ts
Labels: 🐝 Front-end, 🛠 fix

#29 FE-feat-atoms-doyeon 이슈#1 atomic 요소 개발 완료
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/asserts/img/bee-logo.png
  client/src/asserts/img/logo.png
  client/src/asserts/svg/csv.svg.tsx
  client/src/asserts/svg/information.svg.tsx
  client/src/asserts/svg/message.svg.tsx
  client/src/components/atoms/button/IconDetailButton/IconDetailButton.stories.tsx
  client/src/components/atoms/button/IconDetailButton/IconDetailButton.tsx
  client/src/components/atoms/button/IconDetailButton/index.ts
  client/src/components/atoms/button/RoundButton/RoundButton.stories.tsx
  client/src/components/atoms/button/RoundLongButton/RoundLongButton.stories.tsx
  client/src/components/atoms/button/RoundShortButton/RoundShortButton.stories.tsx
  client/src/components/atoms/button/SquircleShortButton/SquircleShortButton.stories.tsx
  client/src/components/atoms/button/TextButton/TextButton.stories.tsx
  client/src/components/atoms/div/AccountBookBackground/AccountBookBackground.stories.tsx
  client/src/components/atoms/div/AccountBookBackground/AccountBookBackground.tsx
  client/src/components/atoms/div/AccountBookBackground/index.ts
  client/src/components/atoms/img/BeeLogo/BeeLogo.stories.tsx
  client/src/components/atoms/img/BeeLogo/BeeLogo.tsx
  client/src/components/atoms/img/BeeLogo/index.ts
  client/src/components/atoms/img/Logo/Logo.stories.tsx
  client/src/components/atoms/img/Logo/Logo.tsx
  client/src/components/atoms/img/Logo/index.ts
  client/src/components/atoms/img/UserImage/UserImage.stories.tsx
  client/src/components/atoms/img/UserImage/UserImage.tsx
  client/src/components/atoms/img/UserImage/index.ts
  client/src/components/atoms/span/BoldSpan/BoldSpan.stories.tsx
  client/src/components/atoms/span/BoldSpan/BoldSpan.tsx
  client/src/components/atoms/span/BoldSpan/index.ts
  client/src/theme/color.ts
Labels: ✨ feature, 🐝 Front-end

#25 FE-feat-ShortChips 2종 생성
  client/src/components/atoms/button/CreateButton/CreateButton.stories.tsx
  client/src/components/atoms/div/RoundShortChips/RoundShortChips.stories.tsx
  client/src/components/atoms/div/RoundShortChips/RoundShortChips.tsx
  client/src/components/atoms/div/RoundShortChips/index.ts
  client/src/components/atoms/div/SquircleShortChips/SquircleShortChips.stories.tsx
  client/src/components/atoms/div/SquircleShortChips/SquircleShortChips.tsx
  client/src/components/atoms/div/SquircleShortChips/index.ts
  client/src/theme/color.ts
Labels: ✨ feature, 🐝 Front-end

#26 FE-feat-P태그 Text 9종 생성
  client/src/components/atoms/p/CenterLargeText/CenterLargeText.stories.tsx
  client/src/components/atoms/p/CenterLargeText/CenterLargeText.tsx
  client/src/components/atoms/p/CenterLargeText/index.ts
  client/src/components/atoms/p/CenterNormalText/CenterNormalText.stories.tsx
  client/src/components/atoms/p/CenterNormalText/CenterNormalText.tsx
  client/src/components/atoms/p/CenterNormalText/index.ts
  client/src/components/atoms/p/CenterSmallText/CenterSmallText.stories.tsx
  client/src/components/atoms/p/CenterSmallText/CenterSmallText.tsx
  client/src/components/atoms/p/CenterSmallText/index.ts
  client/src/components/atoms/p/LeftLargeText/LeftLargeText.stories.tsx
  client/src/components/atoms/p/LeftLargeText/LeftLargeText.tsx
  client/src/components/atoms/p/LeftLargeText/index.ts
  client/src/components/atoms/p/LeftNormalText/LeftNormalText.stories.tsx
  client/src/components/atoms/p/LeftNormalText/LeftNormalText.tsx
  client/src/components/atoms/p/LeftNormalText/index.ts
  client/src/components/atoms/p/LeftSmallText/LeftSmallText.stories.tsx
  client/src/components/atoms/p/LeftSmallText/LeftSmallText.tsx
  client/src/components/atoms/p/LeftSmallText/index.ts
  client/src/components/atoms/p/RightLargeText/RightLargeText.stories.tsx
  client/src/components/atoms/p/RightLargeText/RightLargeText.tsx
  client/src/components/atoms/p/RightLargeText/index.ts
  client/src/components/atoms/p/RightNormalText/RightNormalText.stories.tsx
  client/src/components/atoms/p/RightNormalText/RightNormalText.tsx
  client/src/components/atoms/p/RightNormalText/index.ts
  client/src/components/atoms/p/RightSmallText/RightSmallText.stories.tsx
  client/src/components/atoms/p/RightSmallText/RightSmallText.tsx
  client/src/components/atoms/p/RightSmallText/index.ts
  client/src/theme/color.ts
Labels: ✨ feature, 🐝 Front-end

#32 BE-database 연동 & 환경설정
  server/model/db.ts
  server/package-lock.json
  server/package.json
Labels: ✨ feature, 💻 Back-end

#31 FE-feat-atoms-jk 이슈#2 atomic 요소 개발 완료
  client/src/asserts/svg/pencil.svg
  client/src/components/atoms/button/CircleIconButton/CircleiconButton.stories.tsx
  client/src/components/atoms/button/CircleIconButton/CircleiconButton.tsx
  client/src/components/atoms/button/CircleIconButton/index.ts
  client/src/components/atoms/button/HomeButton/HomeButton.stories.tsx
  client/src/components/atoms/button/OAuthButton/OAuthButton.stories.tsx
  client/src/components/atoms/checkbox/CheckBox/CheckBox.stories.tsx
  client/src/components/atoms/checkbox/CheckBox/CheckBox.tsx
  client/src/components/atoms/checkbox/CheckBox/index.ts
  client/src/components/atoms/div/LightYellowBox/LightYellowBox.stories.tsx
  client/src/components/atoms/div/LightYellowBox/LightYellowBox.tsx
  client/src/components/atoms/div/LightYellowBox/index.ts
  client/src/components/atoms/div/YellowBox/YellowBox.stories.tsx
  client/src/components/atoms/div/YellowBox/YellowBox.tsx
  client/src/components/atoms/div/YellowBox/index.ts
  client/src/components/atoms/p/ExpenditureText/ExpenditureText.stories.tsx
  client/src/components/atoms/p/ExpenditureText/ExpenditureText.tsx
  client/src/components/atoms/p/ExpenditureText/index.ts
  client/src/components/atoms/p/IncomeText/IncomeText.stories.tsx
  client/src/components/atoms/p/IncomeText/IncomeText.tsx
  client/src/components/atoms/p/IncomeText/index.ts
  client/src/components/atoms/p/NumberText/NumberText.stories.tsx
  client/src/components/atoms/p/NumberText/NumberText.tsx
  client/src/components/atoms/p/NumberText/index.ts
  client/src/components/atoms/textarea/TextArea/TextArea.stories.tsx
  client/src/components/atoms/textarea/TextArea/TextArea.tsx
  client/src/components/atoms/textarea/TextArea/index.ts
  client/src/utils/numberToMoney.ts
Labels: ✨ feature, 🐝 Front-end

#35 FE-fix build error 수정
  client/src/components/atoms/button/CircleIconButton/CircleiconButton.stories.tsx
Labels: 🛠 fix

#34 FE-fix-리액트 빌드 오류 수정
  client/package-lock.json
  client/package.json
  client/src/components/atoms/button/CreateButton/CreateButton.stories.tsx
  client/src/components/atoms/button/SampleButton/SampleButton.stories.tsx
  client/src/components/atoms/button/SampleButton/SampleButton.tsx
  client/src/components/atoms/button/SampleButton/index.ts
  client/src/components/atoms/checkbox/CheckBox/CheckBox.stories.tsx
  client/src/components/atoms/div/RoundShortChips/RoundShortChips.tsx
Labels: 🐝 Front-end, 🛠 fix

#33 Fe-feat-atoms-jjy button 요소 개발
  client/package-lock.json
  client/package.json
  client/src/asserts/svg/bell.svg.tsx
  client/src/asserts/svg/minus.svg
  client/src/asserts/svg/setting.svg.tsx
  client/src/components/atoms/button/IconButton/IconButton.stories.tsx
  client/src/components/atoms/button/IconButton/IconButton.tsx
  client/src/components/atoms/button/IconButton/index.ts
  client/src/components/atoms/button/NavButton/NavButton.stories.tsx
  client/src/components/atoms/button/NavButton/NavButton.tsx
  client/src/components/atoms/button/NavButton/index.ts
  client/src/components/atoms/hr/Line/Line.stories.tsx
  client/src/components/atoms/hr/Line/Line.tsx
  client/src/components/atoms/hr/Line/index.ts
Labels: ✨ feature, 🐝 Front-end

#40 FE-feat-CircleGraph 컴포넌트 구현
  client/src/components/atoms/graph/CircleGraph/CircleGraph.stories.tsx
  client/src/components/atoms/graph/CircleGraph/CircleGraph.tsx
  client/src/components/atoms/graph/CircleGraph/index.ts
Labels: ✨ feature, 🐝 Front-end

#36 FE-feat-InputMenu
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.stories.tsx
  client/src/components/atoms/input/DropdownMenu/DropdownMenu.tsx
  client/src/components/atoms/input/DropdownMenu/index.ts
  client/src/components/atoms/input/Input/Input.stories.tsx
  client/src/components/atoms/input/Input/Input.tsx
  client/src/components/atoms/input/Input/index.ts
Labels: ✨ feature, 🐝 Front-end

#37 FE-feat-TopNavBar 구현
  client/src/asserts/svg/setting.svg.tsx
  client/src/components/atoms/button/HomeButton/HomeButton.tsx
  client/src/components/atoms/button/NavButton/NavButton.tsx
  client/src/components/organisms/TopNavBar/TopNavBar.stories.tsx
  client/src/components/organisms/TopNavBar/TopNavBar.tsx
  client/src/components/organisms/TopNavBar/index.ts
Labels: ✨ feature, 🐝 Front-end

#39 FE-feat-loginpage 로그인 페이지 UI 개발
  client/src/App.css
  client/src/App.tsx
  client/src/asserts/img/logo.png
  client/src/components/atoms/button/OAuthButton/OAuthButton.tsx
  client/src/components/atoms/div/Background/Background.stories.tsx
  client/src/components/atoms/div/Background/Background.tsx
  client/src/components/atoms/div/Background/index.ts
  client/src/components/atoms/div/ColumnFlexContainer/ColumnFlexContainer.stories.tsx
  client/src/components/atoms/div/ColumnFlexContainer/ColumnFlexContainer.tsx
  client/src/components/atoms/div/ColumnFlexContainer/index.ts
  client/src/components/atoms/div/Content/Content.stories.tsx
  client/src/components/atoms/div/Content/Content.tsx
  client/src/components/atoms/div/Content/index.ts
  client/src/components/atoms/div/LightYellowBox/LightYellowBox.tsx
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.stories.tsx
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.tsx
  client/src/components/atoms/div/RowFlexContainer/index.ts
  client/src/components/atoms/div/YellowBox/YellowBox.tsx
  client/src/components/atoms/img/BeeLogo/BeeLogo.tsx
  client/src/components/atoms/img/Logo/Logo.tsx
  client/src/components/molecules/CenterContent/CenterContent.stories.tsx
  client/src/components/molecules/CenterContent/CenterContent.tsx
  client/src/components/molecules/CenterContent/index.ts
  client/src/components/molecules/DescriptionLine/DescriptionLine.stories.tsx
  client/src/components/molecules/DescriptionLine/DescriptionLine.tsx
  client/src/components/molecules/DescriptionLine/index.ts
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.stories.tsx
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.tsx
  client/src/components/molecules/OAuthButtonList/index.ts
  client/src/components/molecules/YellowOverlapBackground/YellowOverlapBackground.stories.tsx
  client/src/components/molecules/YellowOverlapBackground/YellowOverlapBackground.tsx
  client/src/components/molecules/YellowOverlapBackground/index.ts
  client/src/components/organisms/BeeBackground/BeeBackground.stories.tsx
  client/src/components/organisms/BeeBackground/BeeBackground.tsx
  client/src/components/organisms/BeeBackground/index.ts
  client/src/components/organisms/EasyLogin/EasyLogin.stories.tsx
  client/src/components/organisms/EasyLogin/EasyLogin.tsx
  client/src/components/organisms/EasyLogin/index.ts
  client/src/components/organisms/LogoWithSlogan/LogoWithSlogan.stories.tsx
  client/src/components/organisms/LogoWithSlogan/LogoWithSlogan.tsx
  client/src/components/organisms/LogoWithSlogan/index.ts
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/theme/color.ts
  client/src/views/LoginPage.tsx
  client/src/views/MainPage.tsx
  client/src/views/MyPage.tsx
  client/src/views/NotificationPage.tsx
Labels: ✨ feature, 🐝 Front-end

#38 FE-feat-atoms-jjy 이슈#16 atomic 요소 개발 완료
  client/src/components/atoms/button/RoundShortButton/RoundShortButton.tsx
  client/src/components/atoms/div/ColorLabel/ColorLabel.stories.tsx
  client/src/components/atoms/div/ColorLabel/ColorLabel.tsx
  client/src/components/atoms/div/ColorLabel/index.js
  client/src/components/atoms/div/TextToggleButton/TextToggleButton.stories.tsx
  client/src/components/atoms/div/TextToggleButton/TextToggleButton.tsx
  client/src/components/atoms/div/TextToggleButton/index.ts
  client/src/components/atoms/div/ToggleButton/ToggleButton.stories.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.tsx
  client/src/components/atoms/div/ToggleButton/index.ts
  client/src/components/atoms/p/UnderlineText/UnderlineText.stories.tsx
  client/src/components/atoms/p/UnderlineText/UnderlineText.tsx
  client/src/components/atoms/p/UnderlineText/index.ts
Labels: ✨ feature, 🐝 Front-end

#42 Feat GitHub OAuth 인증 구현
  client/src/components/atoms/button/OAuthButton/OAuthButton.stories.tsx
  client/src/components/atoms/button/OAuthButton/OAuthButton.tsx
  client/src/components/molecules/OAuthButtonList/OAuthButtonList.tsx
  server/app.ts
  server/package-lock.json
  server/package.json
  server/src/interface/index.ts
  server/src/oauth/controller.ts
  server/src/oauth/router.ts
  server/src/oauth/service.ts
Labels: ✨ feature, 🐝 Front-end, 💻 Back-end

#43 콜리타임 : 스토리북 GlobalStyle 적용, 프론트 글씨체 적용
  client/.storybook/preview.js
  client/config/webpack.config.js
  client/src/App.tsx
  client/src/shared/global.tsx
  client/tsconfig.paths.json
Labels: 🐝 Front-end, 🔥 콜리타임

#44 FE-feat-myAccountInfoCard & 콜리타임
  client/src/components/atoms/div/ColumnFlexContainer/ColumnFlexContainer.tsx
  client/src/components/atoms/div/RowFlexContainer/RowFlexContainer.tsx
  client/src/components/atoms/div/SquircleCard/SquircleCard.tsx
  client/src/components/atoms/img/UserImage/UserImage.tsx
  client/src/components/molecules/TwoByTwoChips/TwoByTwoChips.stories.tsx
  client/src/components/molecules/TwoByTwoChips/TwoByTwoChips.tsx
  client/src/components/molecules/TwoByTwoChips/index.ts
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.stories.tsx
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
  client/src/components/organisms/MyAccountInfoCard/index.ts
Labels: ✨ feature, 🐝 Front-end, 🔥 콜리타임

#45 BE-feat naver OAuth API 구현
  server/src/interface/index.ts
  server/src/oauth/controller.ts
  server/src/oauth/router.ts
  server/src/oauth/service.ts
Labels: ✨ feature, 💻 Back-end

#47 콜리타임 : toggle, textToggle 버튼
  client/src/components/atoms/div/TextToggleButton/TextToggleButton.stories.tsx
  client/src/components/atoms/div/TextToggleButton/TextToggleButton.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.stories.tsx
  client/src/components/atoms/div/ToggleButton/ToggleButton.tsx
Labels: 🐝 Front-end, 🔥 콜리타임

#48 FE-fix-circleGraph props type 문제
  client/src/components/organisms/MyAccountInfoCard/MyAccountInfoCard.tsx
Labels: 🐝 Front-end, 🛠 fix, 🦟 bug

#67 FE-feat-mypage-ui Mypage 메뉴 버튼 구현
  client/src/assets/svg/bell.svg.tsx
  client/src/assets/svg/check-piggy-bank.svg.tsx
  client/src/assets/svg/credit-card.svg.tsx
  client/src/assets/svg/csv.svg.tsx
  client/src/assets/svg/fix.svg.tsx
  client/src/assets/svg/hexagon.svg.tsx
  client/src/components/atoms/button/HexagonButton/HexagonButton.stories.tsx
  client/src/components/atoms/button/HexagonButton/HexagonButton.tsx
  client/src/components/atoms/button/HexagonButton/index.ts
  client/src/components/organisms/MyPageMenu/MyPageMenu.stories.tsx
  client/src/components/organisms/MyPageMenu/MyPageMenu.tsx
  client/src/components/organisms/MyPageMenu/index.ts
  client/src/shared/global.tsx
Labels: ✨ feature, 🐝 Front-end
